# Generated by Django 5.0.3 on 2024-04-02 22:48

import django.db.models.deletion
from django.db import migrations, models

# from .models import Category

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                # ('category',models.ForeignKey(Category, on_delete=models.CASCADE, to_field='name')),
            ],
        ),
    ]


# Product.objects.create(name="LEGO Динозавр",price=9000, description="Необычный конструктор подойдет как детям, так и взрослым. Собирать его увлекательно и полезно. Элементы конструктора скрепляются не только сверху/снизу, но и тонкими пазами в торцах элементов. Конструкторы выполнены из высококачественного ABS пластика, который отличается надежностью, прочностью и безопасностью. В собранном виде это очень необычная игрушка, привлекающая внимание детей. Следуйте подробной инструкции, и вы с легкостью соберёт сюжет. Конструируя, ребёнок развивает мелкую моторику рук, познавательную активность и воображение, становиться усидчивее и внимательнее. Миниразмер деталей позволяет добиться невероятной реалистичности у собранных, подобно объемным 3D-пазлам, конструкций. В результате получаются объекты невиданной точности. Игру можно назвать 3D-пиксельарт, ведь из множества миниатюрных деталек можно собрать абсолютно всё!Примечание :Тщательно различайте тип частиц (1,2.3) и цвет. Это Важно!!!", count=77, is_active=True, category=category_3)